//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cocuk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proje
    {
        public int ProjeNo { get; set; }
        public string ProjeAd { get; set; }
        public Nullable<System.DateTime> BaslamaTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<int> GorevNo { get; set; }
    
        public virtual Gorev Gorev { get; set; }
    }
}
